import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Header, Footer } from "@/components/layout";
import "./globals.css";

export const metadata: Metadata = {
	title: "Appointly | Manage your entire appointments workflow",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={"antialiased selection:bg-pink/90 selection:text-black"}
			>
				<Header />
				<Toaster position="top-right" />
				{children}
				<Footer />
			</body>
		</html>
	);
}
