import type { Metadata } from "next";
import { FetchDashboardData } from "@/components/layout";
import { SnackProvider } from "@/components/pages/Schedule";

export const metadata: Metadata = {
	title: "Appointly | Schedule",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SnackProvider>
			<FetchDashboardData>{children}</FetchDashboardData>
		</SnackProvider>
	);
}
