import type { Metadata } from "next";
import { FetchDashboardData } from "../_components/layout/FetchDashboardData";
export const metadata: Metadata = {
  title: "Appointly | Schedule",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <FetchDashboardData>{children}</FetchDashboardData>;
}
